<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-15T19:41:51Z" name="Sample Test Suite" finished-at="2021-07-15T19:42:28Z" duration-ms="37373">
    <groups>
    </groups>
    <test started-at="2021-07-15T19:41:51Z" name="Test Automation" finished-at="2021-07-15T19:42:28Z" duration-ms="37373">
      <class name="test.java.SampleTest">
        <test-method is-config="true" signature="beforeTestMethod()[pri:0, instance:test.java.SampleTest@543588e6]" started-at="2021-07-16T01:11:51Z" name="beforeTestMethod" finished-at="2021-07-16T01:11:51Z" duration-ms="462" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestMethod -->
        <test-method is-config="true" signature="beforeMethodMethod(java.lang.String, java.lang.reflect.Method)[pri:0, instance:test.java.SampleTest@543588e6]" started-at="2021-07-16T01:11:51Z" name="beforeMethodMethod" finished-at="2021-07-16T01:12:20Z" duration-ms="28880" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.SampleTest.sampleMethodForEmailEntering()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodMethod -->
        <test-method signature="sampleMethodForEmailEntering()[pri:0, instance:test.java.SampleTest@543588e6]" started-at="2021-07-16T01:12:20Z" name="sampleMethodForEmailEntering" finished-at="2021-07-16T01:12:26Z" duration-ms="6159" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Page did not Open expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Page did not Open expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at main.java.pageEvents.LoginPageEvents.verifyLoginPageOpened(LoginPageEvents.java:13)
	at test.java.SampleTest.sampleMethodForEmailEntering(SampleTest.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sampleMethodForEmailEntering -->
        <test-method is-config="true" signature="afterMethodMethod(org.testng.ITestResult)[pri:0, instance:test.java.SampleTest@543588e6]" started-at="2021-07-16T01:12:27Z" name="afterMethodMethod" finished-at="2021-07-16T01:12:27Z" duration-ms="658" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sampleMethodForEmailEntering status=FAILURE method=SampleTest.sampleMethodForEmailEntering()[pri:0, instance:test.java.SampleTest@543588e6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodMethod -->
        <test-method is-config="true" signature="afterTestMethod()[pri:0, instance:test.java.SampleTest@543588e6]" started-at="2021-07-16T01:12:27Z" name="afterTestMethod" finished-at="2021-07-16T01:12:28Z" duration-ms="843" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestMethod -->
      </class> <!-- test.java.SampleTest -->
    </test> <!-- Test Automation -->
  </suite> <!-- Sample Test Suite -->
</testng-results>
